### ISSUE TITLE
Two h2 tags?

### ISSUE THREAD

**Issue by jenndroid** [fac20/Week-1-AJNP#15]
We are not sure if it is best practice to have more than one heading of each type re: accessibility?

**Comment by Netceer** [comment]
We think using mulitple instances of h2s, h3s, h4s etc is fine because it allowed us to create a more organised HTML5 outline which helps with accessbility. 

Using one instance of each header can result in a flat HTML5 outline.

You bring up a very good point for potentially not repeating h1 tags.
