### ISSUE TITLE
CSS units

### ISSUE THREAD

**Issue by fairyaksh** [fac20/Week-1-AJNP#17]
Nice use of VW and rem :confetti_ball:

There are a lot of different units in use and it may be easier to have one consistent unit used throughout your css file.

Our advice (quoted by Jack!) would be to 'use rem for everything, or em when the layout of a given element depends its font size.'

This [article](https://zellwk.com/blog/rem-vs-em/) can help regarding this issue for the future!

**Comment by jessica440** [comment]
thanks! We have changed relevant units to rem :)
