### ISSUE TITLE
Use of wildcard * at the beginning of CSS should be avoided if possible

### ISSUE THREAD

**Issue by LiCern** [fac20/Week-1-AJNP#19]

**Comment by LiCern** [comment]
Perhaps just apply the margin and padding to the body tag 

`<div style="width:100%;height:0;padding-bottom:58%;position:relative;"><iframe src="https://giphy.com/embed/7yTqXVALy7Fwk" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/7yTqXVALy7Fwk">via GIPHY</a></p>`

**Comment by LiCern** [comment]
Perhaps apply margin and padding properties to the body tag! :sparkles:

**Comment by jessica440** [comment]
Thank you, we have now fixed this!
