### ISSUE TITLE
Excessive use of IDs in CSS 

### ISSUE THREAD

**Issue by LiCern** [fac20/Week-1-AJNP#25]
Here are 4 very good reasons not to do this:

:space_invader: Class specificity is lower than ID specificity

:space_invader: Classes can be reused

:space_invader: A consistent convention: It's simpler for developers working in a codebase to know that CSS is attached to 
                classes, and that IDs are used for other purposes.

:space_invader: An element can have several classes, but only one ID

**Comment by JoshDAO** [comment]
Sorted. Thank you :+1:
