### ISSUE TITLE
Git accounts

### ISSUE THREAD

**Issue by oliverjam** [fac20/Week-1-AJNP#26]
It looks like you managed your git/GitHub stuff well—you've got a pretty even distribution of commits and good use of issues/PRs ✨ :octocat:

@jessica440 it looks like maybe your local git user isn't configured correctly—you've got commits showing up with 3 different accounts somehow. This happens to people every cohort; I think you just need to make sure your local git user email matches the one on your GitHub account.

**Comment by jessica440** [comment]
I don't know how to fix it! :(

**Comment by oliverjam** [comment]
What do you get if you run `git config --get user.email` in your terminal? I think you need that email address to match the one in your GitHub profile.

You can set this for all your local repos using `git config --global user.email "email@example.com"`.

There's a bit more info here: https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by jessica440** [comment]
I might be doing something wrong but it doesn't show any email address

**Comment by jessica440** [comment]
never mind, I've fixed it! Thanks
