### ISSUE TITLE
Accessibility - menu

### ISSUE THREAD

**Issue by tacotoemeck** [fac20/Week-1-AJNP#27]
You have used a "black star" as your menu button for mobile. I've inspected the site using ChromeVox and when I click on it, all I get from it is "black star". If I was visually impaired, I would not be able to tell if clicking this would open a menu. 

Generally, for menu buttons, you want to be as descriptive as possible. The hamburger menu button is a common way to represent a clickable menu. Having said, you should never on a visual appearance alone.

I can suggest using aria-labels for such situations. You can read more about it here: https://a11y-101.com/development/aria-label

**Comment by jessica440** [comment]
Thank you, we have added the aria-label
